### ISSUE TITLE
TLS protocol

### ISSUE THREAD

**Issue by didsun** [robrichards/wse-php#18]
Hi everyone, is it possible to force the connection through TLS protocol instead SSL? Because with SSL protocol show me this error: "SSL operation failed with code 1. OpenSSL Error messages: error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure". I will be grateful find help.

**Comment by robrichards** [comment]
That has to be done on the PHP level using stream contexts - either passed to the soap constructor or via the libxml2 global stream context. I believe the flags you are looking for are only available in PHP 5.6+. http://docs.php.net/manual/en/migration56.openssl.php#migration56.openssl.crypto-method. It might be possible to play around with the ciphers (still using a stream context) to achieve what you want as well.
