### ISSUE TITLE
What about improving standards compatibility?

### ISSUE THREAD

**Issue by garex** [robrichards/wse-php#22]
Hi Rob!

Im' using your https://github.com/robrichards/wse-php

What do you think about these?

- [x] Put all classes to own namespace namespace RobRichards\WsePhp;
- [x] Remove hardcoded xmlseclibs.php replacing it by robrichards/xmlseclibs
- [x] Remove all *.php files from the package root
- [x] Make all PSR2, PHP 5.3 compatible
- [x] Replace "requires" in examples scripts by standard vendor/autoload.php

**Comment by garex** [comment]
Bad news only that it should be v2.x as namespaces breaks backward compatibility

**Comment by robrichards** [comment]
All set. I branched off the 1.2.x version and update master to 2.x

**Comment by garex** [comment]
Hooray!

Rob Richards, tnx for reviewing this bunch of code ))

**Comment by garex** [comment]
@robrichards One bad is [packagist](https://packagist.org/packages/robrichards/wse-php) still sees old master.

Can you bump it? Or create tags here like 1.2.? and 2.0.0 and publish them to packagist?

**Comment by robrichards** [comment]
done. Thanks!
