### ISSUE TITLE
Patch for /soap-wsa.php

### ISSUE THREAD

**Issue by GoogleCodeExporter** [robrichards/wse-php#3]
```
Change over the createID to correct the namespace from uudi: to urn:uuid:
```

Original issue reported on code.google.com by `egar...@egm.co` on 10 Oct 2012 at 11:29

Attachments:
* [soap-wsa.php.patch](https://storage.googleapis.com/google-code-attachments/wse-php/issue-3/comment-0/soap-wsa.php.patch)

**Comment by robrichards** [comment]
typo already fixed in source
