### ISSUE TITLE
1.2 Release

### ISSUE THREAD

**Issue by UlrichEckhardt** [robrichards/wse-php#34]
Hi!

According to the [forum](https://groups.google.com/forum/#!topic/wse-php/JHlP0N21b2Q), the 1.2 releases have been deleted. However, the message that this branch is still maintained and supported is still there. If there is a reason (security?) to withdraw older releases, please document that, and also don't call that branch supported. If the tags were deleted accidentally, please restore them!

Thanks!

Uli

**Comment by robrichards** [comment]
Am looking into this. I am unsure what happened to the releases to be honest

**Comment by robrichards** [comment]
Looks like I never actually released a 1.2.0 version from its branch. Just did that now and will also be releasing the composer package today
