### ISSUE TITLE
wse-php not working on WSDL with Inclusivenamespaces and prefixlist

### ISSUE THREAD

**Issue by nachodeleon77** [robrichards/wse-php#37]
Im trying to sign a SOAP envelope from a WSDL using WSSESoap PHP plugin. I cant make it work as it throws a 'Hash values do not match' issue. The WSDL is:

https://efactura.dgi.gub.uy:6470/ePrueba/ws_personaGetActEmpresarialPrueba?wsdl

Im calling from

$sc = new MySoap($wsdl);
$out = $sc->Execute(array("Rut"=>"123456789"));

And getting the 'Hash values do not match' error.

I did a research and seems the problem is when canonizing the Body from the envelop as there is using Inclusivenamespace and prefixes list. I get this working request from SOAPUI.

Here is te reference tag pointing to the Body object.

          <ds:Reference URI="#id-99A5113916FE1B896D152461497086267">
            <ds:Transforms>
              <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#">
                <ec:InclusiveNamespaces xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#" PrefixList="dgi"/>
              </ds:Transform>
            </ds:Transforms>
            <ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
            <ds:DigestValue>iWbErI+zKd+Go3r88YKrh+nZmmE=</ds:DigestValue>
          </ds:Reference>

I also tried to Canonize the SOAP BODY with C14N, but didnt work.

Any workaround for that??

**Comment by catrielr** [comment]
I'm with the same problem as you.
Could you do something with this?

**Comment by zonavip** [comment]
idem

**Comment by zonavip** [comment]
I still get the same error:  'Hash values do not match'

**Comment by zonavip** [comment]
> Estoy con el mismo problema que tú.
> ¿Podrías hacer algo con esto?

Hola! tu lo pudiste solucionar de alguna manera?

**Comment by vivianaZuluaga** [comment]
Hi, I get the same error. With SoapUI the service works correctly but when testing with headers generated with wse-php you always get this error. Could someone fix it?
