### ISSUE TITLE
Nonce EncodingType

### ISSUE THREAD

**Issue by philkingston** [robrichards/wse-php#38]
I'm talking to a SOAP service implemented in Axis2 with JAX-WS. The service requires authentication. I can only get the authentication to succeed if I include an EncodingType for the Nonce. If I don't include it, I get a service error.

The Nonce has to look like this:

`<wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">...DATA...</wsse:Nonce>`

I have to inject the parameter in addUserToken() like this:

`$nonceNode->setAttribute('EncodingType', 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary');`

This obviously works for my scenario. Can it be added as default? Would it work for all other scenarios?

**Comment by robrichards** [comment]
This has been added to the library
