### ISSUE TITLE
Require at least 3.0.2 version of robrichards/xmlseclibs

### ISSUE THREAD

**Issue by mhucik** [robrichards/wse-php#43]
Hi, thank you for your package!

I found some security leaks for olders versions of robrichards/xmlseclibs . Do you think you can update dependencies in your composer.json?

For example if you are using newest version of Roave/SecurityAdvisories, they do not let you install your package.

I prepared PR here:  https://github.com/robrichards/wse-php/pull/42
I hope I did it well

Thank you for your work on open source project
Have a great time :)

**Comment by simshaun** [comment]
Just ran into this. Recommend forking wse-php and updating its composer.json to use robrichards/xmlseclibs 3.x until the linked PR is merged.

Then add to your project's composer.json:
```json
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/{{your_username}}/wse-php.git"
    }
  ],
```
