### ISSUE TITLE
Decryption always fails

### ISSUE THREAD

**Issue by Keyur1991** [robrichards/wse-php#51]
I used this example https://github.com/robrichards/wse-php/blob/master/examples/soap-sign-encrypt.php.  I created own Public/Private Keys and followed exact steps in this example. 

The webservice i am using is returning encrypted response. I tried to decrypt the response according to the example. But the decryption always fails and throws me an exception "Failure decrypting Data". 

Could you please help ?

**Comment by robrichards** [comment]
On 4/1/19 7:56 AM, keyur wrote:
>
> I used this example
> https://github.com/robrichards/wse-php/blob/master/examples/soap-sign-encrypt.php.
> I created own Public/Private Keys and followed exact steps in this
> example.
>
> The webservice i am using is returning encrypted response. I tried to
> decrypt the response according to the example. But the decryption
> always fails and throws me an exception "Failure decrypting Data".
>
> Could you please help ?
>

What version of wse-php and xmlseclibs are you using? Possibly need
updated versions? Its really hard to tell without seeing the response
and having the keys to debug.

**Comment by Keyur1991** [comment]
I installed the latest one via composer a week back.

Following steps i performed for signing and encryption.

(1) I used own Private Key for signing
openssl genrsa -aes256 -out myprivatekey.pem 1024

(2) Then tried to use own Public Key for encryption
openssl rsa -in myprivatekey.pem -pubout > mypublickey.pem
  --Using this for encryption shows me message in soap response:  'ASN.1 parse of certificate failed'
 
(3) Last I extracted public key from website.cer file to encrypt and i am getting the encrypted soap response.

But here decryption throws me this exception
**Fatal error: Uncaught Exception: Failure decrypting Data (openssl private) - error:04065072:rsa routines:rsa_ossl_private_decrypt:padding check failed**

If i don't encrypt the soap doc then decryption throws me this exception
**Uncaught Exception: Failure decrypting Data (openssl private) - error:0406506C:rsa routines:rsa_ossl_private_decrypt:data greater than mod len**

**Comment by Keyur1991** [comment]
I have been successful in figure out the issue **rsa_ossl_private_decrypt:data greater than mod len**. 

Also i was not required to encrypt the soap document. But still i am getting encrypted soap response. 
For that i used this example: https://github.com/robrichards/wse-php/blob/master/examples/soap-wsa-example.php

To decrypt the soap response i used below code:
`$doc = new DOMDocument();
        $doc->loadXML($retVal);
        $options = array("keys" => array("private" => array("key" => PRIVATE_KEY, "isFile" => true, "isCert" => false)));
        $objWSSE->decryptSoapDoc($doc, $options);`

Now i am getting this exception:
**Uncaught exception 'Exception' with message 'Failure decrypting Data (openssl private) - error:0407109F:rsa routines:RSA_padding_check_PKCS1_type_2:pkcs decoding error'**

Could please advice what i am doing wrong here ?

**Comment by Keyur1991** [comment]
I fixed the problem it was the wrong key used in signing soap headers and body.
