### ISSUE TITLE
how to sign timestamp

### ISSUE THREAD

**Issue by gmisterk** [robrichards/wse-php#53]
hi all,

I discover soap with wse.
But i  am confronted to a problem, i use a certificat x509 to reach a webservice but this server need a signed timestamp.

Anybody have already tried to sign a timestamp ?

**Comment by thijzert** [comment]
On the off-chance I can save you the three months of debugging I just went through: are you getting the error `A required timestamp is not found`? If so, you may want to try setting the Content-Type of your transport request to `text/xml` rather than `application/xml`. (Yes, I'm serious.)

**Comment by robrichards** [comment]
please re-open if there is still an issue. Closing from age
